### PR TITLE
Feature: hideDisabledButtons prop hides inc and dec when input is at max or min

### PR DESCRIPTION
**Pull request by benolayinka**

### CODE REVIEW

**Comment by jacobworrel** [comment]
@benolayinka Thanks for the PR. You can currently achieve this feature by using the `children` render prop:

```
    const min = 0;
    const max = 3;
    return (
      <div>
        <CounterInput max={max} min={min}>
          {({
            decrement,
            handleChangeInput,
            handleBlur,
            increment,
            state: { inputValue, count },
            style,
          }) => (
            <div style={style.wrapperStyle}>
              { count > min && <div onClick={decrement} style={style.btnStyle}>&#8722;</div>}
              <input
                type="text"
                value={inputValue}
                onChange={handleChangeInput}
                onBlur={handleBlur}
                style={style.inputStyle}
              />
              {count < max && <div onClick={increment} style={style.btnStyle}>&#43;</div>}
            </div>
          )}
        </CounterInput>
      </div>
    )
```

**Comment by jacobworrel** [comment]
@benolayinka I don't like the idea of adding a new prop for this use case. I think it makes more sense just to make the increment/decrement buttons disabled or hidden by default when it hits the max.

**Comment by benolayinka** [comment]
In that case, it makes more sense to have them disabled by default.

Thanks to your example, I understand how to use renderChildren to hide
them, but if you're not familiar with that it's difficult, and anyway you
have to dig through the source to realize the elements it is normally
rendered.

Am So., 12. Apr. 2020 um 23:02 Uhr schrieb Jacob Worrel <
notifications@github.com>:

**Comment by benolayinka** [comment]
> @benolayinka Thanks for the PR. You can currently achieve this feature by using the `children` render prop:
> 
> ```
>     const min = 0;
>     const max = 3;
>     return (
>       <div>
>         <CounterInput max={max} min={min}>
>           {({
>             decrement,
>             handleChangeInput,
>             handleBlur,
>             increment,
>             state: { inputValue, count },
>             style,
>           }) => (
>             <div style={style.wrapperStyle}>
>               { count > min && <div onClick={decrement} style={style.btnStyle}>&#8722;</div>}
>               <input
>                 type="text"
>                 value={inputValue}
>                 onChange={handleChangeInput}
>                 onBlur={handleBlur}
>                 style={style.inputStyle}
>               />
>               {count < max && <div onClick={increment} style={style.btnStyle}>&#43;</div>}
>             </div>
>           )}
>         </CounterInput>
>       </div>
>     )
> ```

i think this won't quite work because when the dec button isn't rendered, the other elements shift over in the flexbox. In my PR, I just apply a style to make the elements invisible.

**Comment by jacobworrel** [comment]
@benolayinka You can do the same thing in the renderChildren function. Just apply a visibility hidden style on increment/decrement divs instead of conditionally rendering them like I did in the snippet above.

**Comment by jacobworrel** [comment]
closing due to inactivity

**Pull request closed without merging**
